"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}

Review checklist before committing an autogenerated migration:
  * every table and column you expected is present, and nothing you did not
    expect (a surprise `drop_table` usually means a missing import in
    app/db/base_models.py)
  * indexes exist on every foreign key and on any column used in a WHERE clause
  * `downgrade()` actually reverses `upgrade()`
  * no data loss on downgrade, or a comment saying why it is acceptable
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
${imports if imports else ""}

# revision identifiers, used by Alembic.
revision: str = ${repr(up_revision)}
down_revision: str | None = ${repr(down_revision)}
branch_labels: str | Sequence[str] | None = ${repr(branch_labels)}
depends_on: str | Sequence[str] | None = ${repr(depends_on)}


def upgrade() -> None:
    """Apply the change."""
    ${upgrades if upgrades else "pass"}


def downgrade() -> None:
    """Reverse the change."""
    ${downgrades if downgrades else "pass"}
