"""0003 sprint 2 tables

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-11 02:55:16.782580+00:00

Adds the six Sprint 2 tables (S2-F01): feedback, notifications,
transparency_posts, post_comments, bulk_pickups, collection_schedules.
Autogenerated against the Sprint 2 models (S2-F02/F03/F04) and reviewed
against this checklist before committing:
  * every table and column expected is present, and nothing unexpected
    (a surprise `drop_table` usually means a missing import in
    app/db/base_models.py) — confirmed clean, only the six new tables
  * indexes exist on every foreign key and on any column used in a WHERE
    clause — confirmed (see per-table batch_alter_table blocks below)
  * `downgrade()` actually reverses `upgrade()` — confirmed, drops tables
    in reverse dependency order (post_comments before transparency_posts,
    etc.)
  * no data loss on downgrade: these are brand-new tables with no
    production data yet, so a downgrade drop is safe
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ward_id', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.String(length=50), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=True),
    sa.Column('week_of_month', sa.SmallInteger(), nullable=True),
    sa.Column('time_slot', sa.String(length=50), nullable=True),
    sa.Column('is_exception', sa.Boolean(), nullable=False),
    sa.Column('exception_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collection_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_schedules_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_schedules_is_exception'), ['is_exception'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_schedules_ward_id'), ['ward_id'], unique=False)

    op.create_table('bulk_pickups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=False),
    sa.Column('ward_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('load_band', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('preferred_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('fee', sa.Float(), nullable=False),
    sa.Column('assigned_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('assigned_worker_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['assigned_worker_id'], ['workers.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bulk_pickups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bulk_pickups_assigned_vehicle_id'), ['assigned_vehicle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bulk_pickups_assigned_worker_id'), ['assigned_worker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bulk_pickups_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_bulk_pickups_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bulk_pickups_requested_by_user_id'), ['requested_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bulk_pickups_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bulk_pickups_ward_id'), ['ward_id'], unique=False)

    op.create_table('feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('submitted_by_user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_complaint_id'), ['complaint_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_feedback_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_submitted_by_user_id'), ['submitted_by_user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('related_complaint_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['related_complaint_id'], ['complaints.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_related_complaint_id'), ['related_complaint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('transparency_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('ward_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('before_photo_url', sa.String(length=2048), nullable=True),
    sa.Column('after_photo_url', sa.String(length=2048), nullable=True),
    sa.Column('applause_count', sa.Integer(), nullable=False),
    sa.Column('posted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['posted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transparency_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transparency_posts_complaint_id'), ['complaint_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_transparency_posts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transparency_posts_posted_by_user_id'), ['posted_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transparency_posts_ward_id'), ['ward_id'], unique=False)

    op.create_table('post_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['transparency_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_comments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_comments_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_comments_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the change."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_comments_user_id'))
        batch_op.drop_index(batch_op.f('ix_post_comments_post_id'))
        batch_op.drop_index(batch_op.f('ix_post_comments_id'))

    op.drop_table('post_comments')
    with op.batch_alter_table('transparency_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transparency_posts_ward_id'))
        batch_op.drop_index(batch_op.f('ix_transparency_posts_posted_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_transparency_posts_id'))
        batch_op.drop_index(batch_op.f('ix_transparency_posts_complaint_id'))

    op.drop_table('transparency_posts')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_related_complaint_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_submitted_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_complaint_id'))

    op.drop_table('feedback')
    with op.batch_alter_table('bulk_pickups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bulk_pickups_ward_id'))
        batch_op.drop_index(batch_op.f('ix_bulk_pickups_status'))
        batch_op.drop_index(batch_op.f('ix_bulk_pickups_requested_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_bulk_pickups_id'))
        batch_op.drop_index(batch_op.f('ix_bulk_pickups_category'))
        batch_op.drop_index(batch_op.f('ix_bulk_pickups_assigned_worker_id'))
        batch_op.drop_index(batch_op.f('ix_bulk_pickups_assigned_vehicle_id'))

    op.drop_table('bulk_pickups')
    with op.batch_alter_table('collection_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_schedules_ward_id'))
        batch_op.drop_index(batch_op.f('ix_collection_schedules_is_exception'))
        batch_op.drop_index(batch_op.f('ix_collection_schedules_id'))

    op.drop_table('collection_schedules')
    # ### end Alembic commands ###
