"""Pydantic v2 DTOs — the API contract for requests and responses."""

from app.schemas.auth import LoginRequest, RefreshTokenRequest, Token
from app.schemas.common import (
    ErrorDetail,
    ErrorPayload,
    ErrorResponse,
    Page,
    PageMeta,
    error_response,
)
from app.schemas.complaint import (
    ComplaintBase,
    ComplaintCreate,
    ComplaintFilter,
    ComplaintRead,
    ComplaintStatus,
    ComplaintStatusHistoryRead,
    ComplaintSubmit,
    ComplaintUpdate,
)
from app.schemas.resources import (
    EquipmentBase,
    EquipmentCreate,
    EquipmentRead,
    EquipmentStatus,
    EquipmentUpdate,
    VehicleBase,
    VehicleCreate,
    VehicleRead,
    VehicleStatus,
    VehicleUpdate,
    WorkerBase,
    WorkerCreate,
    WorkerRead,
    WorkerStatus,
    WorkerUpdate,
)
from app.schemas.task import TaskBase, TaskCreate, TaskRead, TaskStatus, TaskUpdate
from app.schemas.user import UserCreate, UserRead, UserUpdate
from app.schemas.ward import WardBase, WardCreate, WardRead, WardUpdate

__all__ = [
    "ComplaintBase",
    "ComplaintCreate",
    "ComplaintFilter",
    "ComplaintRead",
    "ComplaintStatus",
    "ComplaintStatusHistoryRead",
    "ComplaintSubmit",
    "ComplaintUpdate",
    "ErrorDetail",
    "ErrorPayload",
    "ErrorResponse",
    "EquipmentBase",
    "EquipmentCreate",
    "EquipmentRead",
    "EquipmentStatus",
    "EquipmentUpdate",
    "LoginRequest",
    "Page",
    "PageMeta",
    "RefreshTokenRequest",
    "TaskBase",
    "TaskCreate",
    "TaskRead",
    "TaskStatus",
    "TaskUpdate",
    "Token",
    "UserCreate",
    "UserRead",
    "UserUpdate",
    "VehicleBase",
    "VehicleCreate",
    "VehicleRead",
    "VehicleStatus",
    "VehicleUpdate",
    "WardBase",
    "WardCreate",
    "WardRead",
    "WardUpdate",
    "WorkerBase",
    "WorkerCreate",
    "WorkerRead",
    "WorkerStatus",
    "WorkerUpdate",
    "error_response",
]
